version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iris-api-image
    container_name: iris-api-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app

